# Site settings
title: I Forum Patriotyzmu Ekonomicznego
email: kontakt@forumpatriotyzmuekonomicznego.pl
description: > # this means to ignore newlines until "baseurl:"
  Zapraszamy Państwa do udziału w I Forum Patriotyzmu Ekonomicznego! Zapraszamy przedsiębiorców, badaczy, a także entuzjastów świadomej konsumpcji gotowych do dyskusji nad wielką Społeczną Grą Zespołową ważną dla naszego kraju, jakim jest patriotyzm ekonomiczny. Spotkajmy się w Toruniu, w Wyższej Szkole Bankowej.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://forumpatriotyzmuekonomicznego.pl" # the base hostname & protocol for your site
permalink: wiadomosci/:title.html
markdown: kramdown
prose:
  siteurl: 'http://forumpatriotyzmuekonomicznego.pl/'
  media: 'foto'
  ignore: ['_includes','_layouts','_sass','css','img','js','formularz.html','wiadomosci.html','.gitignore','_config.yml','CNAME','README.md','android-chrome-144x144.png','android-chrome-192x192.png','android-chrome-36x36.png','android-chrome-48x48.png','android-chrome-72x72.png','android-chrome-96x96.png','apple-touch-icon-114x114.png','apple-touch-icon-120x120.png','apple-touch-icon-144x144.png','apple-touch-icon-152x152.png','apple-touch-icon-180x180.png','apple-touch-icon-57x57.png','apple-touch-icon-60x60.png','apple-touch-icon-72x72.png','apple-touch-icon-76x76.png','apple-touch-icon-precomposed.png','apple-touch-icon.png','browserconfig.xml','favicon-16x16.png','favicon-194x194.png','favicon-32x32.png','favicon-96x96.png','favicon.ico','feed.xml','manifest.json','mstile-144x144.png','mstile-150x150.png','mstile-310x150.png','mstile-310x310.png','mstile-70x70.png']
